version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "8000:8000"
    command: uvicorn job_tracker.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MONGO_URI: "mongodb+srv://antonmongo:tk4BttNC3jJh5fm@cluster0.w2qsk7g.mongodb.net/?retryWrites=true&w=majority"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongo

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
  mongo-data:
